name: Generate & Deploy Documentation
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Set release tag
      run: | 
        export RELEASE_TAG_VERSION=${{ github.event.release.tag_name }}
        echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION:1}" >> $GITHUB_ENV
    - name: Setup doc deploy
      run: |
        git config --global user.name Docs deploy
        git config --global user.email docs@dummy.bot.com
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        git fetch origin gh-pages --depth=1
        git config user.name github-actions
        git config user.email github-actions@github.com
        pip install -r requirements.txt
        python setup.py install
        pip install -r requirements-dev.txt
        pip install mkdocs-material mike # 
        mike deploy --push --update-aliases ${RELEASE_TAG_VERSION} latest
